apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceName: "prometheus"
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      # hostNetwork: true # --- 修改点：删除此行 ---
      # dnsPolicy: ClusterFirstWithHostNet # --- 修改点：删除此行，默认使用 ClusterFirst ---
      serviceAccountName: prometheus
      securityContext:
        fsGroup: 2000
        runAsUser: 0 
        runAsGroup: 0
      nodeSelector:
        kubernetes.io/hostname: "k8s-master" 
      containers:
      - name: prometheus
        image: 192.168.137.97:8086/hthx/prometheus:v2.54.1-arm64
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--web.enable-lifecycle"
          - "--storage.tsdb.retention.time=15d"
          - "--web.enable-remote-write-receiver" # 关键：开启接收功能
          - "--query.lookback-delta=30s"
        ports:
          - containerPort: 9090
            hostPort: 9090
            name: web # --- 修改点：删除 hostPort ---
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus
          - name: storage-volume
            mountPath: /prometheus
          - name: timezone
            mountPath: /etc/localtime
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
        - name: storage-volume
          hostPath:
            path: /data/prometheus 
            type: DirectoryOrCreate
        - name: timezone
          hostPath:
            path: /etc/localtime